=head1 NAME

Sys::Manage::CmdEscort - Sys::Manage::Cmd command execution escort


=head1 SYNOPSIS


  perl -e"use Sys::Manage::CmdEscort; CmdEscort([@ARGV])" -option log/name command line

  eval{Sys::Manage::CmdEscort::CmdEscort([-option, log/name, command line])};


=head1 DESCRIPTION

Used internally by L<Sys::Manage::Cmd|Sys/Manage/Cmd>
for loggings and redirections,
as escort of each command execution on each target element.


=head1 LICENSE

This is free software; 
you can use redistribute it and/or modify it 
under the same terms as Perl itself.



=head1 AUTHOR

Andrew V Makarow <makarow at mail.com>

=cut

