=head1 NAME

Sys::Manage - Systems management commands/scripts environment


=head1 DESCRIPTION

L<Sys::Manage::Cmd|Sys/Manage/Cmd> - Systems management command volley

L<Sys::Manage::Conn|Sys/Manage/Conn> - Connection to remote Perl

L<Sys::Manage::Schedule|Sys/Manage/Schedule> - Scriptic schedule trunk

See particular modules.


=head1 LICENSE

This is free software; 
you can use redistribute it and/or modify it 
under the same terms as Perl itself.


=head1 VERSION

=over


=item '2006-02-17'

Publishing 0.52 version, some corrections made.


=item '2005-12-20'

Publishing 0.51 version.

L<Sys::Manage::Cmd|Sys/Manage/Cmd>: 
new C<cmdfile> predefined command;
C<cmd> and C<daemonize> methods;
C<-gx> and C<-u> options;
C<-vc>, C<-vt>, C<-lg>, C<-lv>, C<-lw> options extensions.

L<Sys::Manage::Conn|Sys/Manage/Conn>:
new C<agtfile> and C<lcmd> methods and commands.

L<Sys::Manage::Schedule|Sys/Manage/Schedule>:
new C<cmdfck> method.


=item '2005-11-25'

Publishing 0.50 version.


=item '2005-09-09'

Started


=back


=head1 AUTHOR

Andrew V Makarow <makarow at mail.com>

=cut

